name: "Test"
on:
  pull_request:
    # Only run on PRs into release
    branches:
    - 'release'

jobs:

  linux-test:
    runs-on: ubuntu-latest
    steps:
    - name: "Install dependencies"
      run: |
        sudo apt update -y
        sudo apt install -y libsdl2-dev libsdl2-image-dev

    - name: "Checkout sources"
      uses: actions/checkout@v3

    - name: "Compile"
      run: |
        make -j3 bin/brogue

    - name: "Check that replays still play back"
      run: |
        python3 test/run_regression_tests.py --num_processes=3 test/regression_test_ce_v1_14/
        python3 test/run_regression_tests.py --num_processes=3 --extra_args "--variant rapid_brogue" test/regression_test_rb_v1_6/
        python3 test/run_regression_tests.py --num_processes=3 --extra_args "--variant bullet_brogue" test/regression_test_bb_v1_1/

    - name: "Check that seed catalogs are unchanged"
      run: |
        python3 test/compare_seed_catalog.py test/seed_catalogs/seed_catalog_brogue.txt 40
        python3 test/compare_seed_catalog.py --extra_args "--variant rapid_brogue" test/seed_catalogs/seed_catalog_rapid_brogue.txt 10
        python3 test/compare_seed_catalog.py --extra_args "--variant bullet_brogue" test/seed_catalogs/seed_catalog_bullet_brogue.txt 5
